#!/usr/bin/env bash

ffmpeg -version > /dev/null 2>&1
if [ $? = 127 ]; then
  echo "ffmpeg is not installed. install ffmpeg to use video2gif function."
  exit 127
fi

function video2gif() {
  ffmpeg -y -i "${1}" -vf fps=${3:-10},scale=${2:-320}:-1:flags=lanczos,palettegen "${1}.png"
  ffmpeg -i "${1}" -i "${1}.png" -filter_complex "fps=${3:-10},scale=${2:-320}:-1:flags=lanczos[x];[x][1:v]paletteuse" "${1}".gif
  rm "${1}.png"
}

video2gif "$@"
